---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
- name: bbr-pipeline-tasks-repo
- name: pipeline

run:
  path: bbr-pipeline-tasks-repo/ci/tasks/validate-pipeline/task.sh

params:
  PIPELINE_PATH:
  SECRETS_PATH:
